version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - docker/.env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13-alpine
    env_file:
      - docker/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
