# Generated by Django 5.0.4 on 2024-05-03 20:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("clinic_name", models.CharField(max_length=255)),
                ("physician_name", models.CharField(max_length=255)),
                ("physician_contact", models.EmailField(max_length=254)),
                ("patient_first_name", models.CharField(max_length=255)),
                (
                    "patient_last_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("patient_dob", models.DateField()),
                (
                    "patient_contact",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("chief_complaint", models.TextField()),
                ("consultation_notes", models.TextField()),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
